Feature/create login
juanpmont07/DailyBudgetBack pull request #1
Opened 2023-05-31 02:44 UTC by alex18franco

2023-05-31 20:23 UTC, juanpmont07 requested changes

2023-05-31 20:23 UTC, juanpmont07 commented on src/main/java/com/dailybudget/budgetapi/domain/service/UserServiceD.java
> +public class UserServiceD {
Se le fue una D al final del nombre

2023-05-31 20:23 UTC, juanpmont07 commented on src/main/java/com/dailybudget/budgetapi/domain/service/UserServiceD.java
> +        return userLoginRepository.register(userLogin);
Un servicio de aplicación si puede tener varias cosas unidas pero en este caso lo recomdable es que en los servicios de dominio si haya un desgloce mas ya que ahora no hay tantos metodos y se entiende pero cuando se crezca el dominio de usuario va ser mas dificil y escalable lo mejor seria crear un servicio de dominio para solo las cosas de user login lo que mas adelante tambien se va crecer cuando empecemos  a manejar tokens, conexiones a aws, etc.

2023-05-31 20:23 UTC, juanpmont07 commented on src/main/java/com/dailybudget/budgetapi/infrastructure/adapters/controllers/UserController.java
> +@RequiredArgsConstructor
Esto que hace?

2023-05-31 20:23 UTC, juanpmont07 commented on src/main/java/com/dailybudget/budgetapi/infrastructure/adapters/controllers/UserController.java
> +    @PostMapping("/login")
No seria un login si no un Register.

2023-05-31 20:23 UTC, juanpmont07 commented on src/main/java/com/dailybudget/budgetapi/application/command/user/CreateUserLogin.java
> +    private UserLoginMapper userInfoMapper;
Renombre la variable tiene que ser UserLogin no UserInfo

2023-05-31 22:32 UTC, alex18franco commented on src/main/java/com/dailybudget/budgetapi/domain/service/UserServiceD.java
> +public class UserServiceD {
parce es que no sabía como diferenciar el UserService de aplicación con el de dominio, me parecio muy pelle el mismo nombre, pero me dices si lo dejo igual

2023-05-31 22:35 UTC, alex18franco commented on src/main/java/com/dailybudget/budgetapi/infrastructure/adapters/controllers/UserController.java
> +@RequiredArgsConstructor
anotación de lombok que maneja los costructores de las variables que tienes o injectas, en este caso estas
    @Autowired
    private final CreateUserInfo createUserInfo;

    @Autowired
    private final CreateUserLogin createUserLogin;

2023-05-31 22:36 UTC, alex18franco commented on src/main/java/com/dailybudget/budgetapi/infrastructure/adapters/controllers/UserController.java
> +    @PostMapping("/login")
puedo dejarlo com registerLogin ? pero recuerdas que te deciá que sería bueno evaluar si en el futuro existira un solo login

2023-06-07 15:08 UTC, juanpmont07 approved these changes

2023-06-07 15:08 UTC, juanpmont07 commented on src/main/java/com/dailybudget/budgetapi/domain/service/UserServiceD.java
> +public class UserServiceD {
Entonces estamos mal por que servicios de aplicación deben ser nombre de acción por ejemplo tengo un servicio de aplicación que se llama registrarUsuarioService no podemos englobar muchas funciones en una sola solo en el dominio ya todo va en un mismo contexto

2023-06-07 15:08 UTC, juanpmont07 commented on src/main/java/com/dailybudget/budgetapi/infrastructure/adapters/controllers/UserController.java
> +    @PostMapping("/login")
Melo

2023-06-07 15:08 UTC, juanpmont07 commented on src/main/java/com/dailybudget/budgetapi/domain/service/UserServiceD.java
> +public class UserServiceD {
Nunca un servicio de aplicación va tener muchos métodos o se va llamar nombreService se crea servicio de aplicación por acción y si es necesario de un servicio de aplicación llamar a otros de una pero la idea es que con esto sea escalable

2023-06-07 15:08 UTC, merged